### ISSUE TITLE
Libcoreclr not found

### ISSUE THREAD

**Issue by mayconbeserra** [joe-elliott/netcore-kubernetes-profiling#7]
Hi Joe,

I'm running one of your examples with perfcollect, but I got the following error:

```
root@d37ee4ac6c1a:~# ./perfcollect collect sample -collectsec 30
/usr/bin/perf: line 13: exec: perf_4.4: not found
E: linux-perf-4.4 is not installed.
Collection started. Collection will automatically stop in 30 second(s). Press CTRL+C to stop early.

...STOPPED.

Starting post-processing. This may take some time.

/usr/bin/perf: line 13: exec: perf_4.4: not found
E: linux-perf-4.4 is not installed.
Generating native image symbol files
/usr/bin/perf: line 13: exec: perf_4.4: not found
E: linux-perf-4.4 is not installed.
libcoreclr.so not found in perf data. Please verify that your .NET Core process is running and consuming CPU.
Saving native symbols
/usr/bin/perf: line 13: exec: perf_4.4: not found
E: linux-perf-4.4 is not installed.
...FINISHED
Exporting perf.data file
...FINISHED
Compressing trace files
...FINISHED
Cleaning up artifacts
...FINISHED

Trace saved to sample.trace.zip
```

I'm using your docker image to inspect my .net core 2.1 app.

Could you tell me what it's wrong?

Thanks in advance

**Comment by joe-elliott** [comment]
Sure, so it appears the kernel you're running on is 4.4.  Please run `uname -r` to confirm.

I've been keeping notes about getting perf and other tools installed on various kernels here:

https://github.com/joe-elliott/netcore-kubernetes-profiling/tree/master/kernel-interactions

A good first attempt would just be:
```
apt-get install linux-tools-4.4
```
or
```
apt-get install linux-perf-4.4
```
If those fail we can work at finding a debian repo or debian repo archive to point at which has the appropriate tools for 4.4.

Perhaps jessie?

**Comment by mayconbeserra** [comment]
Hi Joe,

Kernel is 4.4.21-69-default, and unfortunately, I tried both commands you mentioned but they didn't work. It is not able to find linux-tools-4.4

**Comment by joe-elliott** [comment]
So this is mostly horrible but try:
```
apt-get install linux-perf-4.9
cp /usr/bin/perf_4.9 /usr/bin/perf_4.4
```

**Comment by mayconbeserra** [comment]
LOL, so, I did that already and then started getting the message below:

libcoreclr.so not found in perf data

```
root@0a79f4da9c3e:~# ./perfcollect collect sample -collectsec 30 -pid 29806
Collection started. Collection will automatically stop in 30 second(s). Press CTRL+C to stop early.

...STOPPED.

Starting post-processing. This may take some time.

failed to open perf.data: No such file or directory  (try 'perf record' first)
Generating native image symbol files
failed to open perf.data: No such file or directory  (try 'perf record' first)
libcoreclr.so not found in perf data. Please verify that your .NET Core process is running and consuming CPU.
Saving native symbols
failed to open perf.data: No such file or directory  (try 'perf record' first)
...FINISHED
Exporting perf.data file
...FINISHED
Compressing trace files
...FINISHED
Cleaning up artifacts
...FINISHED

Trace saved to sample.trace.zip
```

My dockerfile is:

```
FROM mcr.microsoft.com/dotnet/core/sdk:2.1.801-stretch

WORKDIR /root

ENV PATH="${PATH}:/root/.dotnet/tools"

RUN  echo deb http://cloudfront.debian.net/debian sid main >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y \
            git \
            bpfcc-tools \
            lttng-tools \
            liblttng-ust-dev \
            procps \
            lldb \
            zip \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth=1 https://github.com/BrendanGregg/FlameGraph \
    && curl -OL https://aka.ms/perfcollect \
    && chmod +x ./perfcollect \
    && dotnet tool install -g dotnet-dump --version 3.0.0-preview7.19365.2 \
    && dotnet tool install -g dotnet-symbol

RUN apt-get update \
    && ./perfcollect install \
    && apt-cache search linux-tools \
    && apt-get -y install linux-headers-4.9.0-11-all linux-perf-4.9

RUN mkdir mySymbols \
    && dotnet symbol --symbols --output ./mySymbols /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/lib*.so \
    && cp ./mySymbols/* /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12
```

Any ideas why libcoreclr.so is not found? It's inside /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12

Thanks again, Joe. I'm with a production issue and I found your article easy to understand, just fighting now to run with containers

**Comment by joe-elliott** [comment]
Let's try something simpler.  perfcollect can be finicky.  Get the pid of your dotnet process and run:

```
perf record -g -p <pid>
<wait a few seconds then ctrl+c>
perf script
```
See if that prints out stack traces.  If it does then perf is generally working.  Next I'd try:
```
perf record -g -p <pid>
<wait a few seconds then ctrl+c>
perf script | FlameGraph/stackcollapse-perf.pl | FlameGraph/flamegraph.pl > flamegraph.svg
```
and see if you can generate a decent flamegraph.  (use `kubectl cp` to retrieve the svg)

Also, I noticed that you passed a pid to perfcollect.sh.  It used to have a bug where it would fail if you passed a pid.  So, perhaps try without that:  https://github.com/joe-elliott/netcore-kubernetes-profiling/tree/master/perfcollect#warning

> Any ideas why libcoreclr.so is not found?

The error "libcoreclr.so not found in perf data." is because the script didn't find any perf data:  "failed to open perf.data: No such file or directory  (try 'perf record' first)".

I'd also recommend pulling the `sample.trace.zip` that perfcollect created even if there was an error.  There will be a `perfcollect.log` in the root of the zip with the commands run and their output.

**Comment by mayconbeserra** [comment]
Hi @joe-elliott 

`perf record -g -p <pid>` doesn't work.

Result message is:

![image](https://user-images.githubusercontent.com/911493/66950628-08172180-f059-11e9-9dc5-f851071d61a0.png)

If I remove `pid`, it works, but it doesn't get any information about the dotnet process. It got from different process inside the VM, but not for dotnet.

I also tried to open sample.trace.zip with Perfview but I got some errors when opening it:

```
---> (Inner Exception #1) System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Diagnostics.Tracing.StackSources.LinuxPerfScriptEventParser.<NextEvent>d__30.MoveNext()
   at Diagnostics.Tracing.StackSources.LinuxPerfScriptEventParser.<Parse>d__9.MoveNext()
   at Diagnostics.Tracing.StackSources.ParallelLinuxPerfScriptStackSource.<>c__DisplayClass1_1.<DoInterning>b__0(Object givenArrayIndex)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

I'm wondering why perf record -p -g doesn't work in my case. I'm running those commands inside a docker container with privileged.

The microservice used for that investigation has the properties set correctly:
COMPlus_EnableEventLog=1
COMPlus_ZapDisable=1
COMPlus_PerfMapEnabled=1

If I use your docker image, shouldn't it work with perfcollect? Should I have something also on VM level set?

**Comment by joe-elliott** [comment]
> If I use your docker image, shouldn't it work with perfcollect? Should I have something also on VM level set?  

Unsure, maybe we'll find a setting at the VM level that requires tweaking.

> I also tried to open sample.trace.zip with Perfview but I got some errors when opening it:  

Just open it as a zip and you'll be able to get the perfcollect.log

That's an awfully large pid.  From within your sidecar what is the result of `ps aux` ?  I feel like you're executing that from the host?  Also I see the beginning of the usage printout which occurs if perf can't find a process with the supplied pid.

**Comment by mayconbeserra** [comment]
Hi @joe-elliott thanks for your help.

I managed to resolve the issue. I didn't mount correctly the volume and used the wrong pid.

I can see the flame graphs and open via PerfView, However, I can't see the garbage collector events as you have in your screenshot at https://github.com/joe-elliott/netcore-kubernetes-profiling/tree/master/perfcollect#perfview

I got the following error when opening the trace.zip:

```
PerfView Start Time 10/23/2019 3:31:04 AM
Started: View
Warning: PdbScope not found at C:\Users\IEUser\Downloads\PerfViewExtensions\PdbScope.exe
Disabling the Image Size Menu Item.
Warning: ILSize not found at C:\Users\IEUser\Downloads\PerfViewExtensions\ILSize.dll
Disabling the IL Size Menu Item.
Completed: View   (Elapsed Time: 0.062 sec)
Started: Opening sample-15-new.trace.zip
Creating ETLX file C:\Users\IEUser\AppData\Local\Temp\PerfView\sample-15-new.trace_70894bf8.etlx from C:\Users\IEUser\Downloads\sample-15-new.trace.zip
Error: Exception CTF conversion: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at Microsoft.Diagnostics.Tracing.CtfTraceEventSource..ctor(String fileName)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CreateFromLttngTextDataFile(String filePath, String etlxFilePath, TraceLogOptions options)
   at PerfView.LinuxPerfViewData.GetTraceLog(TextWriter log)
[Error: exception while opening CTF (lttng) data.]
Completed: Opening sample-15-new.trace.zip   (Elapsed Time: 0.062 sec)
```

Is it because my container doesn't have access to lttng?

I'm running the sidecar like: 

`docker run -it --cap-add ALL --privileged --pid=container:9a3146f94e3a --net=container:9a3146f94e3a -v shared-vehicles-lttng:/var/run/lttng  -v shared-tmp-vehicles:/tmp -v /srv/mpip/perf:/perf private-dtr.com/perf-monitoring:sidecar`

**Comment by joe-elliott** [comment]
You're injecting the sidecar dynamically?  Nice.  I've never done it that way but always assumed it was possible.

For me sharing `/var/run/lttng` has always been sufficient to get lttng working (which I see your in your command).  In fact, it's always been one of the easier utilities to get working b/c it's all in userspace.

I would exec into your sidecar and manually run the following to see if you can get lttng events with your setup.
```
lttng create session --output=./lttng-events
lttng enable-event --userspace --all
lttng track --pid=<pid> -u
lttng start
lttng stop
lttng destroy
babeltrace ./lttng-events
```

For me when the lttng session is running the folder contains the following.
```
root@sample-netcore-app:~# ls -al /var/run/lttng/
total 28
drwxr-xr-x 5 root tracing 4096 Oct 24 13:00 .
drwxr-xr-x 1 root root    4096 Oct 23 20:43 ..
-rw-rw-rw- 1 root root       5 Oct 24 13:00 agent.port
srw-rw---- 1 root tracing    0 Oct 24 13:00 client-lttng-sessiond
drwxr-x--- 2 root tracing 4096 Oct 24 13:00 kconsumerd
-rw-r----- 1 root root       0 Oct 24 13:00 lttng-sessiond.lck
-rw-r--r-- 1 root root       5 Oct 24 13:00 lttng-sessiond.pid
srw-rw-rw- 1 root root       0 Oct 24 13:00 lttng-ust-sock-7
srw-rw---- 1 root tracing    0 Oct 24 13:00 sessiond-health
srw-rw---- 1 root tracing    0 Oct 24 13:00 sessiond-notification
drwxr-x--- 2 root tracing 4096 Oct 24 13:00 ustconsumerd32
drwxr-x--- 2 root tracing 4096 Oct 24 13:00 ustconsumerd64
```

Have you checked the `perfcollect.log` in the root of perfcollect zip?  You should be able to see lttng output there.

**Comment by mayconbeserra** [comment]
Hi @joe-elliott yes, we have a cronjob to run the sidecar for us.

About lttng, it seems it managed to generate the files as your previous comment:

```
total 8
drwxr-xr-x 1 root  102 314 Oct 23 14:00 .
drwxr-xr-x 1 root root  10 Oct 23 11:15 ..
-rw-rw-rw- 1 root root   5 Oct 23 14:00 agent.port
srw-rw---- 1 root  102   0 Oct 23 14:00 client-lttng-sessiond
drwxr-x--- 1 root  102  10 Oct 23 14:00 kconsumerd
-rw-r----- 1 root root   0 Oct 23 11:18 lttng-sessiond.lck
-rw-r--r-- 1 root root   5 Oct 23 14:00 lttng-sessiond.pid
srw-rw-rw- 1 root root   0 Oct 23 14:00 lttng-ust-sock-7
srw-rw---- 1 root  102   0 Oct 23 14:00 sessiond-health
srw-rw---- 1 root  102   0 Oct 23 14:00 sessiond-notification
drwxr-x--- 1 root  102  10 Oct 23 14:00 ustconsumerd32
drwxr-x--- 1 root  102  36 Oct 23 14:00 ustconsumerd64
```

However, you are right, there is something wrong when generating the samples. I haven't had any error message while running perfcollect about crossgen, but it seems there is an issue with it.

I attached the perfcollect.log below.

Example of error:
```
/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Diagnostics.DiagnosticSource.dll
Running /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/crossgen /r :/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.IO.MemoryMappedFiles.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/Microsoft.CSharp.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Security.Cryptography.Cng.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Globalization.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Numerics.Vectors.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Web.HttpUtility.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.IO.Pipes.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Security.Cryptography.OpenSsl.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Security.Cryptography.Encoding.dll:::::/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Text.Encoding.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Collections.NonGeneric.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Security.Cryptography.X509Certificates.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Threading.ThreadPool.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Threading.Timer.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Net.NetworkInformation.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Reflection.Emit.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Net.Mail.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Net.Security.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Xml.XPath.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Diagnostics.Process.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Xml.ReaderWriter.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Runtime.Serialization.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Reflection.Metadata.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Net.Sockets.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Linq.Queryable.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Reflection.Extensions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Diagnostics.Debug.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.ComponentModel.Annotations.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Transactions.Local.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Data.Common.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Reflection.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Reflection.Emit.Lightweight.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Reflection.Emit.ILGeneration.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Text.RegularExpressions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Threading.Thread.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Diagnostics.TraceSource.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Runtime.Serialization.Formatters.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Security.Principal.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Security.Cryptography.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Security.Cryptography.Algorithms.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Private.Xml.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Private.Xml.Linq.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Xml.XDocument.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/Microsoft.Win32.Registry.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Collections.Immutable.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/Microsoft.Win32.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Net.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Net.Http.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Threading.Tasks.Extensions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Security.Claims.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Resources.ResourceManager.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.IO.FileSystem.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.AppContext.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Reflection.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Drawing.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Collections.Specialized.dll::/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Runtime.Numerics.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.ObjectModel.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.ComponentModel.TypeConverter.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Buffers.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Memory.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Linq.Expressions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Diagnostics.Tracing.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Collections.Concurrent.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.ComponentModel.Primitives.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.IO.FileSystem.Watcher.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Diagnostics.DiagnosticSource.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.ComponentModel.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Threading.Tasks.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Runtime.InteropServices.RuntimeInformation.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Text.Encoding.Extensions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Runtime.InteropServices.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Collections.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.IO.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Net.NameResolution.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Linq.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Diagnostics.StackTrace.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Private.Uri.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Threading.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Runtime.Extensions.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.IO.FileSystem.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Console.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/netstandard.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Runtime.dll:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Private.CoreLib.dll: /CreatePerfMap . /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.12/System.Diagnostics.DiagnosticSource.dll
Invalid parameter: /r
```

[perfcollect.log](https://github.com/joe-elliott/netcore-kubernetes-profiling/files/3769411/perfcollect.log)

Have you had this issue? would it be related to https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md#resolving-framework-symbols?

Many thanks, Joe

**Comment by joe-elliott** [comment]
Seems odd that perfcollect is running crossgen.  It shouldn't need to do that if you're setting:

`COMPlus_ZapDisable=1`

This will prevent JIT compilation of the framework and put all necessary symbols in your perfmap in `/tmp`.  Also I don't think LTTng needs symbols.  It gets all the information it needs in the events it receives over the socket.

I reviewed your `perfcollect.log` and I'm not seeing an LTTng errors.  If you don't mind sharing your perfcollect.zip file I'll poke around some:  number101010@gmail.com

Also, this environment variable has to be set in your application container to generate LTTng events.  
`COMPlus_EnableEventLog=1`

Be sure both of the above environments variables are set in your application container and not your sidecar.

**Comment by joe-elliott** [comment]
@mayconbeserra  Have you all had any luck with LTTng?

I'm giving a presentation at Kubecon next week on this material and was hoping to discuss your situation some.  Dynamically injecting the sidecar through Docker is very different from my normal approach and definitely worth noting as an alternative method.

**Comment by joe-elliott** [comment]
Closing due to inactivity
